config/routes.rb
TunrRails::Application.routes.draw do

  root to: "artists#index"

  resources :artists, only: [:index, :create, :new, :edit, :show, :update]
  resources :albums, only: [:index, :create, :new, :edit, :show, :update] do
  	resources :songs, only: [:new, :edit]  	
  end

  resources :songs, only: [:index, :create, :update, :show, :edit]

  get "/artists/:id/destroy" => 'artists#destroy', as: 'artist_destroy'
  get "/albums/:id/destroy" => 'albums#destroy', as: 'album_destroy'
  get "/songs/:id/destroy" => 'songs#destroy', as: 'song_destroy'

  # get "/songs" => 'songs#index'
  # get "/albums" => 'albums#index'
  # get "/artists" => 'artists#index'

end

#            root      /                                          artists#index
#         artists GET  /artists(.:format)                         artists#index
#                 POST /artists(.:format)                         artists#create
#      new_artist GET  /artists/new(.:format)                     artists#new
#     edit_artist GET  /artists/:id/edit(.:format)                artists#edit
#          artist GET  /artists/:id(.:format)                     artists#show
#                 PUT  /artists/:id(.:format)                     artists#update
#     album_songs GET  /albums/:album_id/songs(.:format)          songs#index
#  new_album_song GET  /albums/:album_id/songs/new(.:format)      songs#new
# edit_album_song GET  /albums/:album_id/songs/:id/edit(.:format) songs#edit
#          albums GET  /albums(.:format)                          albums#index
#                 POST /albums(.:format)                          albums#create
#       new_album GET  /albums/new(.:format)                      albums#new
#      edit_album GET  /albums/:id/edit(.:format)                 albums#edit
#           album GET  /albums/:id(.:format)                      albums#show
#                 PUT  /albums/:id(.:format)                      albums#update
#           songs POST /songs(.:format)                           songs#create
#            song GET  /songs/:id(.:format)                       songs#show
#                 PUT  /songs/:id(.:format)                       songs#update
#  artist_destroy POST /artists/:id/destroy(.:format)             artists#destroy
#   album_destroy POST /albums/:id/destroy(.:format)              albums#destroy
#    song_destroy POST /songs/:id/destroy(.:format)               songs#destroy

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :artist_id, :genre, :title
  belongs_to :artist
  has_many :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :bio, :name
  has_many :albums
  has_many :songs, through: :albums
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :album_id, :title
  belongs_to :album
  has_one :artist, through: :album
end

app/controllers/albums_controller.rb
#          albums POST /albums(.:format)                          albums#create
#       new_album GET  /albums/new(.:format)                      albums#new
#      edit_album GET  /albums/:id/edit(.:format)                 albums#edit
#           album GET  /albums/:id(.:format)                      albums#show
#                 POST /albums/:id/destroy(.:format)             albums#destroy
#                 POST /albums/:id/destroy(.:format)              albums#destroy
#                 POST /songs/:id/destroy(.:format)               songs#destroy



class AlbumsController < ApplicationController
	def index
		@albums = Album.all
	end

	def create
		album = Album.new params[:album]
		if album.save
			redirect_to album_path album
		else
			redirect_to new_album_path
		end
	end

	def new
		@album = Album.new
		@artists_select = Artist.all.map { |a| [a.name, a.id] }
	end

	def edit
		@album = Album.find params[:id] 
		@artists_select = Artist.all.map { |a| [a.name, a.id] }
	end

	def update
		album = Album.find params[:id]
		album.update_attributes params[:album]
		redirect_to album_path album
	end

	def show
		@album = Album.find params[:id]
	end

	def destroy
		album = Album.find params[:id]
		album.destroy
		redirect_to albums_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
#            root      /                                          artists#index
#         artists GET  /artists(.:format)                         artists#index
#                 POST /artists(.:format)                         artists#create
#      new_artist GET  /artists/new(.:format)                     artists#new
#     edit_artist GET  /artists/:id/edit(.:format)                artists#edit
#          artist GET  /artists/:id(.:format)                     artists#show

# touch new.html.erb edit.html.erb show.html.erb _form.html.erb _model.html.erb

class ArtistsController < ApplicationController

	def index
		@artists = Artist.all
	end

	def create
		artist = Artist.new params[:artist]
		if artist.save
			redirect_to artist_path artist
		else
			redirect_to new_artist_path
		end
	end

	def new
		@artist = Artist.new
	end

	def edit
		@artist = Artist.find params[:id] 
	end

	def update
		artist = Artist.find params[:id]
		artist.update_attributes params[:artist]
		redirect_to artist_path artist
	end

	def show
		@artist = Artist.find params[:id]
	end

	def destroy
		artist = Artist.find params[:id]
		artist.destroy
		redirect_to artists_path
	end

end

app/controllers/songs_controller.rb
#     album_songs POST /albums/:album_id/songs(.:format)          songs#create
#  new_album_song GET  /albums/:album_id/songs/new(.:format)      songs#new
# edit_album_song GET  /albums/:album_id/songs/:id/edit(.:format) songs#edit
#      album_song GET  /albums/:album_id/songs/:id(.:format)      songs#show

class SongsController < ApplicationController
	def index
		@songs = Song.all
	end

	def create
		song = Song.new params[:song]
		if song.save
			redirect_to song_path song
		else
			redirect_to new_song_path
		end
	end

	def new
		@song = Song.new
		@album_id = params[:album_id]
	end

	def edit
		@song = Song.find params[:id] 
		@album_id = params[:album_id]
		
	end

	def update
		song = Song.find params[:id]
		song.update_attributes params[:song]
		redirect_to song_path song
	end

	def show
		@song = Song.find params[:id]
	end

	def destroy
		song = Song.find params[:id]
		song.destroy
		redirect_to songs_path
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_album.html.erb
<h3><%= link_to album.title, album_path( album ) %></h3>
<hr>
<div class="description">
	<h5>Genre:</h5>
	<p><%= album.genre %></p>
	<h5>Artist:</h5>
	<p><%= album.artist.name %></p>
</div>
<h5>SONGZ</h5>
<div class="description">
<% album.songs.each do |song| %>

<p>-<%= link_to song.title, song_path( song ) %></p>

<% end %>
</div>
<div class="edit-link">
<%= link_to '[edit]', edit_album_path( album ) %>
</div>

app/views/albums/_form.html.erb
<div class="four columns">
	<%= form_for @album do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :genre %>
	<%= f.text_field :genre %>
	<%= f.label :artist_id %>
	<%= f.select :artist_id, options_for_select( @artists_select ) %>
	<%= f.submit %>

	<% end %>
</div>

app/views/albums/edit.html.erb
<div class="offset-by-four four columns">
	<h2>Edit your <span class="freal">Album</span>...</h2>
	<h4>(analbumcover...)</h4>
</div>

<%= render 'form' %>

app/views/albums/index.html.erb
<div class="offset-by-three five columns">
<h2>See your <span class="freal">Albums!</span></h2>
<h4 class="add-bottom">(analbumcover...)</h4>
<%= link_to "New Album", new_album_path, class: 'button' %>

</div>

<div class="five columns">

<%= render @albums %>

</div>

app/views/albums/new.html.erb
<div class="offset-by-four four columns">
	<h2>Create your <span class="freal">Album</span>...</h2>
	<h4>(analbumcover...)</h4>
</div>

<%= render 'form' %>

app/views/albums/show.html.erb
<div class="offset-by-three five columns">
<h2>See your <span class="freal">Album!</span></h2>
<h4 class="add-bottom">(analbumcover...)</h4>
<%= link_to "New Song", new_album_song_path( @album ), class: 'button' %>

</div>

<div class="five columns">

<%= render @album %>

</div>

app/views/artists/_artist.html.erb
<h3><%= link_to artist.name, artist_path( artist ) %></h3>
<hr>
<!-- <h4 class="description-title">Bio:</h4> -->
<div class="description">
<p><%= artist.bio %></p>
</div>

<h5 class="description-title">Albums:</h5>
<div class="description">
<% artist.albums.each do |album| %>
-<%= link_to album.title, album_path( album ) %>

<% end %>

</div>
<div class="edit-link">
<%= link_to '[edit]', edit_artist_path( artist ) %>
</div>

app/views/artists/_form.html.erb
<div class="four columns">
	<%= form_for @artist do |f| %>

	<%= f.label :name  %>
	<%= f.text_field :name %>
	<%= f.label :bio %>
	<%= f.text_area :bio %>
	<%= f.submit %>

	<% end %>
</div>

app/views/artists/edit.html.erb
<div class="offset-by-four four columns">
	<h2>Edit your <span class="freal">Artist</span>...</h2>
	<h4>(hooray...)</h4>
</div>

<%= render 'form' %>

app/views/artists/index.html.erb
<div class="offset-by-three five columns">
<h2>See your <span class="freal">Artists!</span></h2>
<h4 class="add-bottom">(hooray...)</h4>
<%= link_to "New Artist", new_artist_path, class: 'button' %>

</div>

<div class="five columns">

<%= render @artists %>

</div>

app/views/artists/new.html.erb
<div class="offset-by-four four columns">
	<h2>Create your <span class="freal">Artist</span>...</h2>
	<h4>(hooray...)</h4>
</div>

<%= render 'form' %>

app/views/artists/show.html.erb
<div class="offset-by-three five columns">
<h2>See your <span class="freal">Artist!</span></h2>
<h4>(hooray...)</h4>

</div>

<div class="five columns">

<%= render @artist %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TunrRails</title>
  

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<header class="sixteen columns">
			<div id="header-content">
				<div class="row">
					<h1 class="title sixteen columns alpha omega remove-bottom">Tunr: type in your tunez</h1>
				</div>
				<div class="row">
					<div class="offset-by-three thirteen columns alpha omega">
						<div class="row remove-bottom">
							<nav>

								<div class="five columns alpha" >
									<%= link_to "Artists", artists_path, class: "nav-link" %>	
								</div>
								
								<div class="five columns omega" >
									<%= link_to 'Albums', albums_path, class: "nav-link" %>									
								</div>

							</nav>
						</div>
					</div>
				</div>
			</div>
		</header>
		<br class="clear">
		
		<%= yield %>
		
		<br class="clear add-bottom">
		<hr>
		<div class="offset-by-six four columns">
			<p class="best-friend">Tunr is your best friend...</p>
		</div>

</body>
</html>

app/views/songs/_form.html.erb
<div class="four columns">
	<%= form_for @song do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.hidden_field :album_id, value: @album_id %>

	<%= f.submit %>

	<% end %>
</div>

app/views/songs/_song.html.erb
<h3><%= link_to song.title, song_path( song )%></h3>
<hr>
<div class="description">
	<h5>Album:</h5>
	<p><%= song.album.title %></p>
	<h5>Artist:</h5>
	<p><%= song.artist.name %></p>
</div>
<div class="edit-link">
<%= link_to '[edit]', edit_song_path( song ) %>
</div>

app/views/songs/edit.html.erb
<div class="offset-by-four four columns">
	<h2>Edit your <span class="freal">Song</span>...</h2>
	<h4>(songtastical...)</h4>
</div>

<%= render 'form' %>

app/views/songs/index.html.erb
<div class="offset-by-three five columns">
<h2>See your <span class="freal">Songs!</span></h2>
<h4>(songtastical...)</h4>



</div>

<div class="five columns">

<%=  render @songs %>

</div>

app/views/songs/new.html.erb
<div class="offset-by-four four columns">
	<h2>Create your <span class="freal">Song</span>...</h2>
	<h4>(songtastical...)</h4>
</div>

<%= render 'form' %>

app/views/songs/show.html.erb
<div class="offset-by-three five columns">
<h2>See your <span class="freal">Song!</span></h2>
<h4>(songtastical...)</h4>

</div>

<div class="five columns">

<%= render @song %>

</div>